workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: codemagic   # 你已經設好的整合，沿用

    environment:
      ios_signing:
        distribution_type: app_store
        # 這裡一定要跟 Xcode 專案/Info.plist 的 Bundle Identifier 一樣
        bundle_identifier: com.taipeiads.todate.webview
      vars:
        # ✅ 使用 Apple ID（數字），不是 Bundle ID
        APP_APPLE_ID: "6751520810"      # 到 App Store Connect > App > App Information > Apple ID
        IOS_SCHEME: "Runner"
      flutter: stable
      # 建議固定 Xcode 版本以避免突發更新（例：16.2）
      xcode: 16.2
      cocoapods: default

    scripts:
      - name: Set up code signing (use Codemagic-managed profiles)
        script: |
          xcode-project use-profiles

      - name: Prebuild: Flutter & CocoaPods & Info.plist sanity
        script: |
          set -euxo pipefail
          flutter --version
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get
          # 建議把啟動畫面保持正確（不要刪 SceneManifest）
          INFO_PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :UILaunchStoryboardName LaunchScreen" "$INFO_PLIST" || true
          # 安裝 Pods
          cd ios
          pod repo update
          pod install
          cd -
          # 印出 Info.plist 方便除錯
          plutil -p "$INFO_PLIST" || true

      - name: (Optional) Lint & tests
        script: |
          flutter analyze
          flutter test
        ignore_failure: true

      - name: Get next build number from TestFlight and set it
        script: |
          set -euxo pipefail
          # 取最新 TestFlight build number（若沒有，回傳可能為空，做個 fallback）
          LATEST_TF_NUM=$(app-store-connect get-latest-testflight-build-number $APP_APPLE_ID --platform IOS || true)
          if [ -z "${LATEST_TF_NUM:-}" ]; then
            NEXT_BUILD=1
          else
            NEXT_BUILD=$((LATEST_TF_NUM + 1))
          fi
          echo "Using CFBundleVersion: $NEXT_BUILD"
          # 用 agvtool 寫入 Xcode 專案的 build number（需在 ios 專案目錄）
          cd ios
          agvtool new-version -all $NEXT_BUILD
          cd -

      - name: Flutter build ipa (release)
        script: |
          set -euxo pipefail
          # build-name 可綁定 Codemagic 的建置計數或自行維護；這裡先固定 1.0.0
          flutter build ipa \
            --release \
            --build-name=1.0.0 \
            -v
          # ⚠ 不再硬塞 --export-options-plist，交給自動簽章與 Flutter 預設

      - name: Collect Xcode logs (for troubleshooting)
        script: |
          mkdir -p /tmp/xcodebuild_logs || true
          find ~/Library/Logs -name "*.log" -print0 | xargs -0 -I{} cp "{}" /tmp/xcodebuild_logs/ || true
          echo "Xcode logs collected."

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - **/xcodebuild*.log

    publishing:
      email:
        recipients:
          - hank.highlight@gmail.com
        notify:
          success: true
          failure: false
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false
