workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.taipeiads.todate.webview
        team_id: YOUR_APPLE_TEAM_ID   # ← 到 Developer → Membership 看到的 10 碼字母數字
      vars:
        APP_APPLE_ID: "6751520810"    # App Store Connect 裡該 App 的 Apple ID（數字）
        IOS_SCHEME: "Runner"
      flutter: stable
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: "Set up code signing"
        script: |
          # 若你已在 UI 開啟自動簽章，這行會自動抓對 Profile
          xcode-project use-profiles --team-id "$CM_TEAM_ID" || xcode-project use-profiles

      - name: "Prebuild"
        script: |
          set -euxo pipefail
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get
          INFO_PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :UILaunchStoryboardName LaunchScreen" "$INFO_PLIST" || true
          cd ios && pod repo update && pod install && cd -

      - name: "Next build number"
        script: |
          set -euxo pipefail
          LATEST=$(app-store-connect get-latest-testflight-build-number $APP_APPLE_ID --platform IOS || true)
          NEXT=${LATEST:+$((LATEST+1))}
          : "${NEXT:=1}"
          echo "Next build number: $NEXT"
          cd ios && agvtool new-version -all $NEXT && cd -

      - name: "Build IPA"
        script: |
          set -euxo pipefail
          flutter build ipa --release --build-name=1.0.0 -v

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - "/tmp/xcodebuild_logs/*.log"
      - flutter_drive.log
      - "**/xcodebuild*.log"
