platform :ios, '13.0'

use_frameworks! :linkage => :static
use_modular_headers!

# 改用 repo 裡的 ios/Flutter/podhelper.rb
require File.expand_path(File.join(__dir__, 'Flutter', 'podhelper.rb'))

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end
